import pyautogui

pyautogui.moveTo(pyautogui.locateCenterOnScreen('startmenu.PNG'), duration = 1)
pyautogui.sleep(1)
pyautogui.click()
pyautogui.sleep(1)
pyautogui.typewrite('PAINT',interval=1)
pyautogui.sleep(1)
pyautogui.moveTo(pyautogui.locateCenterOnScreen('paint.PNG'), duration = 1)
pyautogui.click()
pyautogui.dragRel(400,0,duration=1)
pyautogui.click()
pyautogui.moveTo(pyautogui.locateCenterOnScreen('brush.PNG'), duration = 0.5)
pyautogui.moveTo(pyautogui.locateCenterOnScreen('brush2.PNG'), duration = 0.5)
pyautogui.click()
pyautogui.click()
pyautogui.moveRel(-260,180, duration = 0.5)
pyautogui.click()
pyautogui.dragRel(400,0,duration=0.2)
pyautogui.dragRel(0,200,duration=0.2)
pyautogui.dragRel(-400,0,duration=0.2)
pyautogui.dragRel(0,-200,duration=0.2)
pyautogui.moveTo(pyautogui.locateCenterOnScreen('abutton.PNG'), duration = 0.5)
pyautogui.click()
pyautogui.moveRel(-104,280, duration = 0.5)
pyautogui.click()
pyautogui.typewrite('BATATA, VAI SE LASCAR',interval=0.2)
pyautogui.moveRel(50,50, duration = 0.3)
pyautogui.click()
